export * from './HeroSection';
export * from './AboutFounder';
export * from './CoursesSection';
export * from './RoadmapSection';
export * from './PricingSection';
export * from './CertificatesSection';
export * from './FeedbacksSection';
export * from './ActivitiesGallery';
export * from './ContactSection';
